name: Docker Push UI

on:
  push:
    branches:
      - main # Or your UI's main branch
    paths:
      - '**' # Only trigger if changes in the trading_ui directory

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (frontend)
        uses: docker/build-push-action@v5
        with:
          push: true
          file: /trading_ui/Dockerfile # Assuming Dockerfile is directly in trading_ui
          context: ./trading_ui          # Context is trading_ui directory
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trading-ui:latest
          no-cache: true
          # Add build-args if needed